PasteboardProject/PasteboardProject/Models/User/User.cs
using System.ComponentModel.DataAnnotations;

namespace PasteboardProject.Models;

public class User
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public string Password { get; set; } = "";
    public string Email { get; set; } = "";
    public DateTime RegistrationDateTime { get; set; }
    public DateTime LastVisitDateTime { get; set; }
    public bool ConfirmedEmail { get; set; }
    public string EmailConfirmationToken { get; set; } = "";
}

PasteboardProject/PasteboardProject/Models/User/ViewModels/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PasteboardProject.Models.ViewModels;

public class EditViewModel
{
    [Required(ErrorMessage = "Введите имя")]
    public string Name { get; set; } = "";
    
    public string Email { get; set; } = "";
    
    [Required(ErrorMessage = "Введите старый пароль")]
    [MinLength(8,ErrorMessage = "Минимальная длина пароля 8")]
    public string OldPassword { get; set; } = "";
    
    [Required(ErrorMessage = "Введите новый пароль")]
    [MinLength(8,ErrorMessage = "Минимальная длина пароля 8")]
    public string Password { get; set; } = "";
    
    [Required]
    [Compare("Password",ErrorMessage = "Не совпадает с паролем")]
    public string ConfirmPassword { get; set; } = "";
}

PasteboardProject/PasteboardProject/Models/User/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
using PasteboardProject.Interfaces;

namespace PasteboardProject.Models.ViewModels;

public class LoginViewModel : ITokenGenerated
{
    [Required(ErrorMessage = "Введите адрес эл.почты")]
    public string Email { get; set; } = "";
    [Required(ErrorMessage = "Неверный пароль")]
    public string Password { get; set; } = "";
}

PasteboardProject/PasteboardProject/Models/User/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
using PasteboardProject.Interfaces;

namespace PasteboardProject.Models.ViewModels;

public class RegisterViewModel : ITokenGenerated
{
    [Required(ErrorMessage = "Введите имя")]
    public string Name { get; set; } = "";
    [Required(ErrorMessage = "Введите адрес эл.почты")]
    public string Email { get; set; } = "";
    [Required(ErrorMessage = "Введите пароль")]
    [MinLength(8,ErrorMessage = "Минимальная длина пароля 8")]
    public string Password { get; set; } = "";
    [Required]
    [Compare("Password",ErrorMessage = "Не совпадает с паролем")]
    public string ConfirmPassword { get; set; } = "";
    
}

PasteboardProject/PasteboardProject/Models/User/ViewModels/UserViewModel.cs
namespace PasteboardProject.Models.ViewModels;

public class UserViewModel
{
    public string Name { get; set; } = "";
    public string Email { get; set; } = "";
    public List<Pasteboard> Pasteboards { get; set; }
}

PasteboardProject/PasteboardProject/Models/User/ViewModels/UsersListViewModel.cs
namespace PasteboardProject.Models.ViewModels;

public class UsersListViewModel
{
    public string Email { get; set; } = "";
    public DateTime RegistrationDate { get; set; }
    public DateTime LastVisitDate { get; set; }
}

PasteboardProject/PasteboardProject/Controllers/PasteboardController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NLog;
using NLog.Fluent;
using PasteboardProject.Exceptions;
using PasteboardProject.Interfaces;
using PasteboardProject.Models;
using PasteboardProject.Models.ViewModels;
using PasteboardProject.Services;

namespace PasteboardProject.Controllers;

[Authorize]
[Route("pasteboard")]
public class PasteboardController : Controller
{
    private readonly IPasteboardRepository _pasteboardRepository;
    private readonly IVisitorRepository _visitorRepository;
    private static readonly Logger Logger = LogManager.GetLogger("PasteboardController");
    public PasteboardController(IPasteboardRepository pasteboardRepository, IVisitorRepository visitorRepository)
    {
        _pasteboardRepository = pasteboardRepository;
        _visitorRepository = visitorRepository;
        Logger.Debug("Logger Init");
    }
    
    [AllowAnonymous]
    [HttpGet("{id}")]
    public async Task<IActionResult> ShowPasteboard(string id)
    {
        Log.Debug($"Метод Show Pasteboard index = {id}");
        try
        {
            var pasteboardById = await _pasteboardRepository.GetPasteboardByIdAsync(id);
            var ip = HttpContext.Connection.RemoteIpAddress?.ToString();
            var userAgent = HttpContext.Request.Headers["User-Agent"].FirstOrDefault();
            var city = await IpInformationService.GetCityFromIp(ip);
            await _visitorRepository.AddPasteboardVisitorToDataBase(ip,city,userAgent,pasteboardById.Id);
            return View(pasteboardById);
        }
        catch (CustomException e)
        {
            Logger.Error($"CustomException: {e.Message}");
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
        catch (Exception e)
        {
            Logger.Error($"{e.Message} {e.StackTrace} {e.Data}");
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }
    
    [HttpGet("create")]
    public IActionResult CreatePasteboardAsync()
    {
        try
        {
            Logger.Debug($"This is CreatePasteboardAsync Action: Get");
            var activePasteboardFields = new List<ActivePasteboardField>();
            var pasteboardViewModel = new PasteboardViewModel
            {
                AspAction = "CreatePasteboardAsync",
                ActivePasteboardFields = AddEmptyFields(activePasteboardFields)
            };
            return View("CreateEditPasteboard",pasteboardViewModel);
        }
        catch (CustomException e)
        {
            Logger.Error($"CustomException: {e.Message}");
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
        catch (Exception e)
        {
            Log.Error($"{e.Data}{e.Message}{e.StackTrace}");
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }
    
    [HttpPost("create")]
    public async Task<IActionResult> CreatePasteboardAsync(PasteboardViewModel pasteboardViewModel)
    {
        try
        {
            Logger.Debug($"This is CreatePasteboardAsync Action: Post");
            var pasteboard = DeleteEmptyFields(pasteboardViewModel);
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            await _pasteboardRepository.SendPasteboardToDataBaseAsync(pasteboard, userEmail);
            return View("ShowPasteboard", pasteboard);
        }
        catch (CustomException e)
        {
            Logger.Error($"CustomException: {e.Message}");
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
        catch (Exception e)
        {
            Log.Error($"{e.Data}{e.Message}{e.StackTrace}");
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }
    
    [HttpGet("edit/{id}")]
    public async Task<IActionResult> EditPasteboardAsync(string id)
    {
        Logger.Debug($"This is EditPasteboard Action: Get");
        try
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var pasteboard = await _pasteboardRepository.GetPasteboardByIdWithUserCheckAsync(id,userEmail);
            var listActivePasteboardFields = pasteboard.PasteboardFields.Select(pasteboardField => new ActivePasteboardField { FieldName = pasteboardField.FieldName, FieldValue = pasteboardField.FieldValue }).ToList();
            var pasteboardViewModel = new PasteboardViewModel
            {
                Name = pasteboard.Name,
                AspAction = "EditPasteboard",
                ActivePasteboardFields = AddEmptyFields(listActivePasteboardFields)
            };
            return View("CreateEditPasteboard", pasteboardViewModel);
        }
        catch (CustomException e)
        {
            Logger.Error($"CustomException: {e.Message}");
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
        catch (Exception e)
        {
            Logger.Error($"Exception: {e.Message} {e.Data} {e.StackTrace}");
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }
    
    [HttpPost]
    [Route("edit/{id}")]
    public async Task<IActionResult> EditPasteboardAsync(PasteboardViewModel pasteboardViewModel)
    {
        try
        {
            Logger.Debug($"This is EditPasteboard Action: Post");
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var pasteboard = DeleteEmptyFields(pasteboardViewModel);
            await _pasteboardRepository.SendPasteboardToDataBaseAsync(pasteboard, userEmail);
            return RedirectToAction("ShowPasteboard", new{pasteboard.Id});
        }
        catch (Exception e)
        {
            Logger.Error($"Exception: {e.Message} {e.Data} {e.StackTrace}");
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
    }
    
    [HttpGet("delete")]
    public async Task<IActionResult> DeletePasteboardAsync(string id)
    {
        try
        {
            Log.Debug("This is DeletePasteboard Action: Get");
            var pasteboard = await _pasteboardRepository.GetPasteboardByIdAsync(id);
            return View("DeletePasteboard",pasteboard);
        }
        catch (Exception e)
        {
            Logger.Error($"Exception: {e.Message} {e.Data} {e.StackTrace}");
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
    }
    
    [HttpPost("delete")]
    public async Task<IActionResult> DeletePasteboardAsync(Pasteboard pasteboard)
    {
        Log.Debug("This is DeletePasteboard Action: Post");
        try
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            await _pasteboardRepository.DeletePasteboardAsync(pasteboard,userEmail);
            return RedirectToAction("UserPage", "User");
        }
        catch (Exception e)
        {
            return View("~/Views/Error/ErrorPage.cshtml", e.Message);
        }
    }
    
    [HttpGet("statistics")]
    public async Task<IActionResult> ShowVisits(int id)
    {
        Log.Debug("This is ShowVisits Action: Get");
        try
        {
            var visitors = await _visitorRepository.GetAllPasteboardVisitors(id);
            return View("VisitStatistics",visitors);
        }
        catch (Exception)
        {
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }

    private List<ActivePasteboardField> AddEmptyFields(List<ActivePasteboardField> activePasteboardField)
    {
        
        var maxFieldCount = 10;
        var activeFieldCount = activePasteboardField
            .Count(pf => pf.FieldName != null && pf.FieldValue != null);
        for (var i = activeFieldCount; i < maxFieldCount; i++)
        {
            activePasteboardField.Add(new ActivePasteboardField());
        }
        if (activeFieldCount == 0)
        {
            for (var i = 0; i < 3; i++)
            {
                activePasteboardField[i].IsActive = true;
            }
        }
        else
        {
            for (int i = 0; i < activeFieldCount; i++)
            {
                activePasteboardField[i].IsActive = true;
            }
        }
        return activePasteboardField;
    }
    private Pasteboard DeleteEmptyFields(PasteboardViewModel pasteboardViewModel)
    {
        var pasteboardFields = new List<PasteboardField>();
        foreach (var activePasteboardField in pasteboardViewModel.ActivePasteboardFields.Where(pf => pf.IsActive))
        {
            pasteboardFields.Add(new PasteboardField
            {
                FieldName = activePasteboardField?.FieldName??"", 
                FieldValue = activePasteboardField?.FieldValue??""
            });
        }
        var pasteboard = new Pasteboard
        {
            Id = pasteboardViewModel.Id,
            Name = pasteboardViewModel.Name,
            PasteboardFields = pasteboardFields
        };

        return pasteboard;
    }

    

   
}

PasteboardProject/PasteboardProject/Controllers/UserController.cs
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using NLog;
using PasteboardProject.Exceptions;
using PasteboardProject.Interfaces;
using PasteboardProject.Models.ViewModels;
using PasteboardProject.Services;

namespace PasteboardProject.Controllers;


[Route("user")]
public class UserController : Controller
{
    private readonly IUserRepository _userRepository;
    private readonly IConfiguration _configuration;
    private readonly IEmailService _emailService;
    private static readonly Logger Logger = LogManager.GetLogger("UserController");
    public UserController(IUserRepository userRepository, IConfiguration configuration, IEmailService emailService)
    {
        _userRepository = userRepository;
        _configuration = configuration;
        _emailService = emailService;

        Logger.Debug("User Controller in");
    }
    
    [HttpGet("register")]
    public IActionResult Register()
    {
        return View();
    }
    
    [HttpPost("register")]
    public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
    {
        try
        {
            if (!ModelState.IsValid) return View(registerViewModel);
            var userExist = await _userRepository.ExistUserInDataBaseAsync(registerViewModel);
            if (userExist)
            {
                ModelState.AddModelError("Email","Эл. почта уже существует, введите другой или войдите");
                return View(registerViewModel);
            }
            await _userRepository.AddUserToDataBaseAsync(registerViewModel);
            var emailToken = await _userRepository.GetUserToken(registerViewModel.Email);
            await _emailService.SendEmailAsync(registerViewModel.Email,emailToken);
            var id = "register";
            return RedirectToAction("VerifyUser", new {id});
        }
        catch (Exception e)
        {
            Logger.Error(e.Message, e.Data, e.StackTrace);
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }

    [HttpGet("login")]
    public IActionResult Login()
    {
        return View("Login");
    }

    [HttpPost("login")]
    public async Task<IActionResult> Login(LoginViewModel loginViewModel)
    {
        if (!ModelState.IsValid) return View(loginViewModel);
        try
        {
            var userEmailConfirmed = await _userRepository.EmailConfirmedCheck(loginViewModel.Email);
            if (!userEmailConfirmed)
            {
                ModelState.AddModelError("Email","Выполните подтверждение аккаунта через эл.почту");
                return View(loginViewModel);
            }
            TokenService.AddTokenToCookie(loginViewModel,_configuration,HttpContext);
            return RedirectToAction("UserPage");
        }
        catch (CustomException)
        {
            ModelState.AddModelError("Email", "Неверный пароль или email");
            ModelState.AddModelError("Password", "Неверный пароль или email");
            return View(loginViewModel);
        }
        catch (Exception e)
        {
            Logger.Error(e.Message, e.Data, e.StackTrace);
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }
    
    [Authorize]
    [HttpGet("logout")]
    public IActionResult Logout()
    {
        TokenService.DeleteTokenFromCookie(HttpContext);
        return RedirectToAction("Index","Home");
    }
    
    [HttpGet("verify/{id}")]
    public async Task<IActionResult> VerifyUser(string id)
    {
        if (id == "register")
        {
            return View("VerifyUser", "Подтвердите аккаунт через эл. почту");
        }
        var tokenConfirmed = await _userRepository.UserTokenConfirmation(id);
        if (!tokenConfirmed) return View("~/Views/Error/ErrorPage.cshtml", CustomException.AccessDeniedMessage);
        return View("VerifyUser","Подтверждение эл.почты прошло успешно, выполните вход для дальнейшей работы");
    }
    
    [Authorize]
    [HttpGet("edit")]
    public IActionResult EditUser()
    {
        var editViewModel = new EditViewModel
        {
            Email = User.FindFirstValue(ClaimTypes.Email)
        };
        return View(editViewModel);
    }
    
    [Authorize]
    [HttpPost("edit")]
    public async Task<IActionResult> EditUser(EditViewModel editViewModel)
    {
        if (!ModelState.IsValid) return View(editViewModel);
        await _userRepository.UpdateUserAsync(editViewModel);
        return RedirectToAction("UserPage");
    }

    [Authorize(Roles = "User, Administrator")]
    [HttpGet("profile")]
    public async Task<IActionResult> UserPage()
    {
        try
        {
            var userViewModel = await _userRepository.GetUserViewModelAuthorizedAsync
                (User.FindFirstValue(ClaimTypes.Email));
            return View(userViewModel);
        }
        catch (Exception e)
        {
            Logger.Error(e.Message, e.Data, e.StackTrace);
            return View("~/Views/Error/ErrorPage.cshtml", CustomException.DefaultMessage);
        }
    }

    [Authorize(Roles = "Administrator")]
    [HttpGet("admin")]
    public async Task<IActionResult> AdminPage()
    {
        var userList = await _userRepository.GetUserListAsync();
        return View("~/Views/Admin/AdminPage.cshtml",userList);
    }
}

PasteboardProject/PasteboardProject/Views/User/CreateUser.cshtml
@model PasteboardProject.Models.ViewModels.UserViewModel;

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Регистрация</p>

<form asp-action="CreateUser" asp-controller="User" method="post">
    <div class="col-4 mx-auto">
        <div class="mb-3">
            <label class="form-label">Имя аккаунта</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <div class="form-text">Введите имя аккаунта</div>
        </div>
        
         <div class="mb-3">
                <label class="form-label">Эл. почта</label>
                <input type="email" asp-for="Email" class="form-control"/>
                <div class="form-text">Введите эл.почту</div>
         </div>

        <div class="mb-3">
            <label class="form-label">Пароль</label>
            <input type="password" asp-for="Password" class="form-control"/>
            <div class="form-text">Введите пароль</div>
        </div>

        <button type="submit" class="btn btn-primary btn-lg">Регистрация</button>
    </div>
</form>

PasteboardProject/PasteboardProject/Views/User/EditUser.cshtml
@model PasteboardProject.Models.ViewModels.EditViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Редактирование профиля</p>

<form asp-action="EditUser" asp-controller="User" method="post">
    <div class="mx-auto">
        <div class="mb-3">
            <label class="form-label">Имя аккаунта</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
            <div class="form-text">Введите имя аккаунта</div>
        </div>

        <div>
            <input type="hidden" asp-for="Email"/>
        </div>
        
        <div class="mb-3">
            <label class="form-label">Старый пароль</label>
            <input type="password" asp-for="OldPassword" class="form-control"/>
            <span asp-validation-for="OldPassword" class="text-danger"></span>
            <div class="form-text">Введите старый пароль</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Новый пароль</label>
            <input type="password" asp-for="Password" class="form-control"/>
            <span asp-validation-for="Password" class="text-danger"></span>
            <div class="form-text">Введите новый пароль</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Новый пароль</label>
            <input type="password" asp-for="ConfirmPassword" class="form-control"/>
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            <div class="form-text">Повторите новый пароль</div>
        </div>

        <button type="submit" class="btn btn-primary btn-lg">Изменить</button>
    </div>
</form>

PasteboardProject/PasteboardProject/Views/User/Login.cshtml
@model PasteboardProject.Models.ViewModels.LoginViewModel;

<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Вход</p>
<form asp-action="Login" asp-controller="User" method="post">
  <div class="mx-auto">
    <div>
        <label class="form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control">
        <span asp-validation-for="Email" class="text-danger"></span>
        <div class="form-text">Введите адрес эл.почты</div>
    </div>
      <div>
          <label class="form-label">Пароль</label>
          <input type="password" asp-for="Password" class="form-control">
          <span asp-validation-for="Password" class="text-danger"></span>
          <div class="form-text">Введите пароль</div>
      </div>
      @* <div> *@
      @*     <a href="@Url.Action("RestorePassword")" id="ember118"> *@
      @*           Напомнить пароль *@
      @*         </a> *@
      @* </div> *@
      
      <button type="submit" class="btn btn-primary btn-lg">Вход</button>
      <a href="@Url.Action("Register")" class="btn btn-secondary btn-lg" >Регистрация </a>
  </div>
</form>

PasteboardProject/PasteboardProject/Views/User/Register.cshtml
@model PasteboardProject.Models.ViewModels.RegisterViewModel;

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Регистрация</p>

<form asp-action="Register" asp-controller="User" method="post">
    
    <div class="mx-auto">
        <div class="mb-3">
            <label class="form-label">Имя аккаунта</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
            <div class="form-text">Введите имя аккаунта</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Эл. почта</label>
            <input type="email" asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
            <div class="form-text">Введите эл.почту</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Пароль</label>
            <input type="password" asp-for="Password" class="form-control"/>
            <span asp-validation-for="Password" class="text-danger"></span>
            <div class="form-text">Введите пароль</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Пароль</label>
            <input type="password" asp-for="ConfirmPassword" class="form-control"/>
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            <div class="form-text">Введите пароль</div>
        </div>
        
        <div class="mb-3">
            Нажимая на кнопку "Регистрация" вы соглашаетесь с <a class="text-dark" asp-controller="Home" asp-action="Policy">Условиями использования и Политикой конфиденциальности</a>
        </div>

        <button type="submit" class="btn btn-primary btn-lg">Регистрация</button>
        <a href="@Url.Action("Login")" class="btn btn-secondary btn-lg" >Вход </a>
    </div>
</form>

PasteboardProject/PasteboardProject/Views/User/RestorePassword.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>RestorePasswordView</h2>

PasteboardProject/PasteboardProject/Views/User/UserPage.cshtml
@model PasteboardProject.Models.ViewModels.UserViewModel;

@{
    Layout = "_Layout";
}

<h2 class="text-center">Страница пользователя: @Model.Name</h2>
<br/>

<h3 class="text-center">Список моих визиток:</h3>
<br/>
<table class="table">
    <thead>
    <tr>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @for (int i = 0; i < Model.Pasteboards.Count;i++)
    {
       <tr>
            <th scope="row"><div class="text-dark nav-link">@(i + 1)</div></th>
            <td><div class="text-dark nav-link">@Model.Pasteboards[i].Name</div></td>
            <td><a class="text-dark nav-link" href="@Url.Action("ShowPasteboard","Pasteboard", new{@Model.Pasteboards[i].Id})">Просмотреть</a></td>
            <td><a class="text-dark nav-link" href="@Url.Action("EditPasteboard","Pasteboard", new{@Model.Pasteboards[i].Id})">Редактировать</a></td>
            <td><a class="text-dark nav-link" href="@Url.Action("DeletePasteboard","Pasteboard",new{@Model.Pasteboards[i].Id})">Удалить</a></td>
            <td><a class="text-dark nav-link" href="@Url.Action("ShowVisits","Pasteboard",new{@Model.Pasteboards[i].Id})">Статистика</a></td>
        </tr>
    }
    </tbody>
</table>
<a class="nav-link text-dark" href="@Url.Action("CreatePasteboard","Pasteboard")">Добавить визитку</a>

PasteboardProject/PasteboardProject/Views/User/VerifyUser.cshtml
@model string

@{
    Layout = "_Layout";
}

<h2>Подтверждение пользователя</h2>
<div>
    @Model
</div>